### ISSUE TITLE
ImportError: cannot import name 'create_autogen_memgpt_agent' from 'memgpt.autogen.memgpt_agent'

### ISSUE THREAD

**Issue by platinaCoder** [cpacker/MemGPT#129]
As the title says function "create_autogen_memgpt_agent". 
I'm not sure why. I've tried testing with your latest example. 
I've installed "pyautogen[teachable]" and "pymemgpt" as the script points out. 

Getting the same error when running without and with environment (both anaconda and python venv).

Conda:
`(autogen) [coding_team]$ python autogen_memgpt_test.py 
Traceback (most recent call last):
  File "/home/$uname/Documents/ai_agents/coding_team/autogen_memgpt_test.py", line 14, in <module>
    from memgpt.autogen.memgpt_agent import create_autogen_memgpt_agent
ImportError: cannot import name 'create_autogen_memgpt_agent' from 'memgpt.autogen.memgpt_agent' (/home/$uname/anaconda3/envs/autogen/lib/python3.10/site-packages/memgpt/autogen/memgpt_agent.py)
`

No env:
`
(base) [coding_team]$ python autogen_memgpt_test.py 
Traceback (most recent call last):
  File "/home/$uname/Documents/ai_agents/coding_team/autogen_memgpt_test.py", line 14, in <module>
    from memgpt.autogen.memgpt_agent import create_autogen_memgpt_agent
ImportError: cannot import name 'create_autogen_memgpt_agent' from 'memgpt.autogen.memgpt_agent' (/home/$uname/.local/lib/python3.11/site-packages/memgpt/autogen/memgpt_agent.py)
(base) [coding_team]$ python autogen_memgpt_test.py 
`

Edit:
I figured I'll update the package as it was running 0.1.2. After updating to 0.1.4 the error is still there. 

Edit 2:
The older way of calling the memgpt agent still works without errors. The only error I get is a 'connection refused':

`Traceback (most recent call last):        
  File "/home/nickdv/anaconda3/envs/autogen/lib/python3.10/site-packages/autogen/oai/completion.py", line 224, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "/home/nickdv/anaconda3/envs/autogen/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)                                                                           
  File "/home/nickdv/anaconda3/envs/autogen/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/home/nickdv/anaconda3/envs/autogen/lib/python3.10/site-packages/openai/api_requestor.py", line 289, in request
    result = self.request_raw(
  File "/home/nickdv/anaconda3/envs/autogen/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in request_raw
    raise error.APIConnectionError(                                                                                  
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x7f3a87741270>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

It seems like it tries to connect to a local api. When I run Ollama with litellm which opens a api on `http://0.0.0.0:8000' it starts working but won't use the actual memgpt agent. Though, I must admit that I'm not sure how the openai library creates the api proxy. Could be easily possible that they open the proxy on the same address. 
I will do some more testing and reading when I'm having a bit more time. 

Edit 3:
After looking through the source code of the class that can't be imported, I now see the "TODO" and "NotImplemented" exception. My bad. 

I'm still running into the connection issues so I'm gonna dive into that for now. Will report back in issue #128 .

**Comment by cpacker** [comment]
@vivi might be due to no package version update?

**Comment by vivi** [comment]
Just bumped the version, please run `pip install pymemgpt -U`
