### ISSUE TITLE
[Evals] letta-evals run command failing with error: "cannot import name 'AgentState' from 'letta_client'"

### ISSUE THREAD

**Issue by Jolie-Ni** [cpacker/MemGPT#3092]
**Describe the bug**
I installed the letta evals lib locally followed the instructions but was running into an error with message"cannot import name 'AgentState' from 'letta_client'". 
All commands with `letta-evals` keywords are failing. Even `letta-evals --version`. So I think the lib might be broken. 

I was originally suspecting python version compability issue. Here are the versions I am using
python version: 3.11.0 (also tried 3.12.0 and 3.13.0 but none works).  

**Please describe your setup**
- [x] How are you running Letta?
  - Docker
  - pip (legacy) **(installed the lib with pip)**
  - From source
  - Desktop
- [x] Describe your setup
  - What's your OS (Windows/**MacOS**/Linux)?
  - What is your `docker run ...` command (if applicable)

**Screenshots**
<img width="1434" height="205" alt="Image" src="https://github.com/user-attachments/assets/0b217938-d021-4120-adc0-df0b108fc434" />

**Comment by Jolie-Ni** [comment]
The issue was on letta-evals v0.7.0. After I upgraded to v0.8.0 it's fixed.
